trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstBuild
  - job: SecondJob
    steps:
    - bash: echo Build SecondBuild

- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeployJob

- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob

- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo ProdDeployJob
  steps: 
  - bash: 
- stage: DevDeploy
- stage: QADeploy
- stage: ProdDeploy

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
